name: Build and Push Docker Images to Docker Hub

on:
  push:
    branches:
      - main  # Trigger this workflow when changes are pushed to the main branch

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository code
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Log in to Docker Hub
      - name: Log in to Docker Hub
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      # Step 3: Build the Docker image for the frontend
      - name: Build Docker image for frontend
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/frontend:latest ./bitcoin-metrics-frontend

      # Step 4: Tag the frontend Docker image
      - name: Tag Docker image for frontend
        run: |
          docker tag ${{ secrets.DOCKER_USERNAME }}/frontend:latest ${{ secrets.DOCKER_USERNAME }}/frontend:latest

      # Step 5: Push the frontend Docker image to Docker Hub
      - name: Push Docker image for frontend to Docker Hub
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/frontend:latest

      # Step 6: Build the Docker image for the backend
      - name: Build Docker image for backend
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/backend:latest ./bitcoin-explore-backend

      # Step 7: Tag the backend Docker image
      - name: Tag Docker image for backend
        run: |
          docker tag ${{ secrets.DOCKER_USERNAME }}/backend:latest ${{ secrets.DOCKER_USERNAME }}/backend:latest

      # Step 8: Push the backend Docker image to Docker Hub
      - name: Push Docker image for backend to Docker Hub
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/backend:latest
